spring.application.name=lms-backend

spring.datasource.url=jdbc:mysql://localhost:3306/lmsdb
spring.datasource.username=lms_user
spring.datasource.password=lms

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8082
